app:
  name: ms-auth
  environment: ${ENV}

security:
  jwt:
    secret: ${JWT_SECRET}
    expiration: 24 # hours
  password:
    cost: 6

data:
  datasource:
    postgres:
      host: ${POSTGRES_HOST}
      port: ${POSTGRES_PORT}
      user: ${POSTGRES_USER}
      password: ${POSTGRES_PASSWORD}
      database: auths

server:
  port: 8080
  read-timeout: 10
  write-timeout: 10
