app:
  name: ms-auth
  environment: ${ENV:standalone}

security:
  jwt:
    secret: ${JWT_SECRET:my-super-secret}
    expiration: 24 # hours
  password:
    cost: 6

data:
  datasource:
    postgres:
      host: ${POSTGRES_HOST:localhost}
      port: ${POSTGRES_PORT}
      user: ${POSTGRES_USER:admin}
      password: ${POSTGRES_PASSWORD:password}
      database: auths

server:
  port: 8080
  read-timeout: 10
  write-timeout: 10
