apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-auth
  template:
    metadata:
      labels:
        app: ms-auth
    spec:
      containers:
        - name: ms-auth
          image: ghcr.io/proyectum/ms-auth:1.0.4
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: 128Mi
              cpu: 250m
            limits:
              memory: 256Mi
              cpu: 500m
          readinessProbe:
            httpGet:
              path: /ping
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /ping
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 20
          env:
            - name: ENV
              value: k8s
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: ms-auth
                  key: PS_HOST
            - name: POSTGRES_PORT
              valueFrom:
                configMapKeyRef:
                  name: ms-auth
                  key: PS_PORT
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  key: POSTGRES_USER
                  name: ms-auth
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ms-auth
                  key: POSTGRES_PASSWORD
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  key: JWT_SECRET
                  name: security

      imagePullSecrets:
        - name: ghcr-secret