apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ms-auth
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /api/v1/auth
            pathType: Prefix
            backend:
              service:
                name: ms-auth
                port:
                  number: 8080
